Repository Ducky-Chickens/bangazon-site, pull requests merged in 2018-04, with the labels that each got.

#23 Add PR template and Issue template.
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  seeders/.gitkeep
Labels: setup

#29 Joe db
  .gitignore
  build-db.js
  config/config.json
  seeders/data/customers.json
  seeders/data/orderProducts.json
  seeders/data/orders.json
  seeders/data/paymentTypes.json
  seeders/data/productTypes.json
  seeders/data/products.json
Labels: setup

#30 user model, data
  build-db.js
  migrations/20171012141344-create-user.js
  migrations/20180419161955-create-user.js
  models/user.js
  seeders/.gitkeep
  seeders/data/users.json
  views/login.pug
  views/partials/user-form.pug
Labels: setup

#31 created models for all tables except users including their associations
  .gitignore
  migrations/20180419155706-create-order.js
  migrations/20180419160223-create-payment-types.js
  migrations/20180419160733-create-product.js
  migrations/20180419161009-create-product-type.js
  migrations/20180419161314-create-order-product.js
  models/PaymentType.js
  models/order.js
  models/orderproduct.js
  models/product.js
  models/producttype.js
  models/user.js
  package-lock.json
  package.json
  seeders/data/products.json
Labels: setup

#33 Hp hash
  build-db.js
  config/passport-strat.js
Labels: setup

#35 Tm readme
  README.md
  package-lock.json
  package.json
  test/seed.js
Labels: setup

#40 linked working stylesheet
  client/css/index.css
  views/index.pug
Labels: setup

#42 login and register on nav
  views/partials/nav.pug
Labels: enhancement

#41 User can view status of products uploaded
  README.md
  app.js
  controllers/authCtrl.js
  controllers/inventoryCtrl.js
  migrations/20180419155917-create-order.js
  routes/authRoute.js
  routes/index.js
  routes/inventoryRoute.js
  seeders/data/orderProducts.json
  views/inventory.pug
  views/partials/nav.pug
Labels: requirement

#45 Hp prod
  README.md
  client/index.css
  client/js/categories.js
  client/js/client.js
  client/js/search.js
  controllers/productSearchCtrl.js
  routes/index.js
  routes/productSearchRoute.js
  views/account.pug
  views/categories.pug
  views/category-products.pug
  views/home.pug
  views/index.pug
  views/partials/nav.pug
  views/productDetails.pug
  views/search.pug
Labels: good first issue

#46 the whole order history feature
  README.md
  build-db.js
  client/js/account.js
  client/js/categories.js
  controllers/accountCtrl.js
  controllers/homeCtrl.js
  controllers/inventoryCtrl.js
  controllers/orderCtrl.js
  models/order.js
  models/orderproduct.js
  models/product.js
  routes/account.js
  routes/index.js
  routes/inventoryRoute.js
  routes/ordersRoute.js
  views/account.pug
  views/accountOrders.pug
  views/inventory.pug
  views/order.pug
Labels: requirement

#47 Implement add/delete payment types
  README.md
  client/js/account.js
  controllers/accountCtrl.js
  routes/account.js
  seeders/data/products.json
  views/account.pug
  views/addPaymentType.pug
Labels: requirement

#53 Hp rm cart product
  README.md
  controllers/cartCtrl.js
  models/PaymentType.js
  routes/cartRoute.js
  seeders/data/orderProducts.json
  seeders/data/orders.json
  views/cart.pug
Labels: $

#54 Completing an Order
  controllers/accountCtrl.js
  controllers/cartCtrl.js
  controllers/orderCtrl.js
  routes/authRoute.js
  routes/cartRoute.js
  views/cart.pug
  views/checkout.pug
  views/complete.pug
  views/inventory.pug
Labels: $, gnarly, requirement, sick

#55 Clear Cart
  README.md
  controllers/cartCtrl.js
  routes/cartRoute.js
  views/cart.pug
Labels: $, enhancement, gnarly, good first issue, requirement, sick

#56 Bug fixes
  controllers/cartCtrl.js
  views/cart.pug
  views/productDetails.pug
Labels: bug
